- name: "Populate NetBox database"
  connection: local
  hosts: localhost
  gather_facts: False
  tasks:
    - name: Create regions
      netbox.netbox.netbox_region:
        netbox_url: "{{ lookup('env', 'NETBOX_API') }}"
        netbox_token: "{{ lookup('env', 'NETBOX_TOKEN') }}"
        data:
          name: "{{ item.name }}"
          parent_region: "{{ item.parent | default(omit) }}"
        state: present
      with_items: "{{ netbox_data.regions }}"
    - name: Create sites
      netbox.netbox.netbox_site:
        netbox_url: "{{ lookup('env', 'NETBOX_API') }}"
        netbox_token: "{{ lookup('env', 'NETBOX_TOKEN') }}"
        data:
          name: "{{ item.name }}"
          region: "{{ item.region | default(omit)}}"
        state: present
      with_items: "{{ netbox_data.sites }}"
    - name: Create device roles
      netbox.netbox.netbox_device_role:
        netbox_url: "{{ lookup('env', 'NETBOX_API') }}"
        netbox_token: "{{ lookup('env', 'NETBOX_TOKEN') }}"
        data:
          name: "{{ item.name }}"
          color: "{{ item.color }}"
        state: present
      with_items: "{{ netbox_data.device_roles }}"
    - name: Create manufacturers
      netbox.netbox.netbox_manufacturer:
        netbox_url: "{{ lookup('env', 'NETBOX_API') }}"
        netbox_token: "{{ lookup('env', 'NETBOX_TOKEN') }}"
        data:
          name: "{{ item.name }}"
        state: present
      with_items: "{{ netbox_data.manufacturers }}"
    - name: Create device types
      netbox.netbox.netbox_device_type:
        netbox_url: "{{ lookup('env', 'NETBOX_API') }}"
        netbox_token: "{{ lookup('env', 'NETBOX_TOKEN') }}"
        data:
          model: "{{ item.name }}"
          manufacturer: "{{ item.manufacturer }}"
        state: present
      with_items: "{{ netbox_data.device_types }}"
    - name: Create tags
      netbox.netbox.netbox_tag:
        netbox_url: "{{ lookup('env', 'NETBOX_API') }}"
        netbox_token: "{{ lookup('env', 'NETBOX_TOKEN') }}"
        data:
          name: "{{ item.name }}"
      with_items: "{{ netbox_data.tags }}"
    - name: Create cluster types
      netbox.netbox.netbox_cluster_type:
        netbox_url: "{{ lookup('env', 'NETBOX_API') }}"
        netbox_token: "{{ lookup('env', 'NETBOX_TOKEN') }}"
        data:
          name: "{{ item.name }}"
      with_items: "{{ netbox_data.cluster_types }}"
    - name: Create clusters
      netbox.netbox.netbox_cluster:
        netbox_url: "{{ lookup('env', 'NETBOX_API') }}"
        netbox_token: "{{ lookup('env', 'NETBOX_TOKEN') }}"
        data:
          cluster_type: "{{ item.type }}"
          name: "{{ item.name }}"
      with_items: "{{ netbox_data.clusters }}"
    - name: Create VLANs
      netbox.netbox.netbox_vlan:
        netbox_url: "{{ lookup('env', 'NETBOX_API') }}"
        netbox_token: "{{ lookup('env', 'NETBOX_TOKEN') }}"
        data:
          name: "{{ item.name }}"
          vid: "{{ item.vid }}"
      with_items: "{{ netbox_data.vlans }}"
    - name: Create VRFs
      netbox.netbox.netbox_vrf:
        netbox_url: "{{ lookup('env', 'NETBOX_API') }}"
        netbox_token: "{{ lookup('env', 'NETBOX_TOKEN') }}"
        data:
          name: "{{ item.name }}"
      with_items: "{{ netbox_data.vrfs }}"
    - name: Create devices
      netbox.netbox.netbox_device:
        netbox_url: "{{ lookup('env', 'NETBOX_API') }}"
        netbox_token: "{{ lookup('env', 'NETBOX_TOKEN') }}"
        data:
          device_role: "{{ item.role }}"
          device_type: "{{ item.type }}"
          name: "{{ item.name }}"
          site: "{{ item.site }}"
          tags: "{{ item.tags | default(omit)}}"
        state: present
      with_items: "{{ netbox_data.devices }}"
    - name: Create device interfaces
      netbox.netbox.netbox_device_interface:
        netbox_url: "{{ lookup('env', 'NETBOX_API') }}"
        netbox_token: "{{ lookup('env', 'NETBOX_TOKEN') }}"
        data:
          device: "{{ item.0.name }}"
          mode: "{{ item.1.mode | default(omit) }}"
          name: "{{ item.1.name }}"
          type: "{{ item.1.type }}"
          untagged_vlan: "{{ item.1.untagged_vlan | default(omit) }}"
          tagged_vlans: "{{ item.1.tagged_vlans | default(omit) }}"
        state: present
      with_subelements:
        - "{{ netbox_data.devices }}"
        - interfaces
    - name: Create VMs
      netbox.netbox.netbox_virtual_machine:
        netbox_url: "{{ lookup('env', 'NETBOX_API') }}"
        netbox_token: "{{ lookup('env', 'NETBOX_TOKEN') }}"
        data:
          cluster: "{{ item.cluster }}"
          name: "{{ item.name }}"
          site: "{{ item.site }}"
          tags: "{{ item.tags | default(omit)}}"
          virtual_machine_role: "{{ item.role }}"
        state: present
      with_items: "{{ netbox_data.virtual_machines }}"
    - name: Create VM interfaces
      netbox.netbox.netbox_vm_interface:
        netbox_url: "{{ lookup('env', 'NETBOX_API') }}"
        netbox_token: "{{ lookup('env', 'NETBOX_TOKEN') }}"
        data:
          virtual_machine: "{{ item.0.name }}"
          name: "{{ item.1.name }}"
        state: present
      with_subelements:
        - "{{ netbox_data.virtual_machines }}"
        - interfaces
    - name: Create device ip addresses
      netbox.netbox.netbox_ip_address:
        netbox_url: "{{ lookup('env', 'NETBOX_API') }}"
        netbox_token: "{{ lookup('env', 'NETBOX_TOKEN') }}"
        data:
          address: "{{ item.1.address }}"
          interface: 
            name: "{{ item.1.name }}"
            device: "{{ item.0.name }}"
          vrf: "{{ item.1.vrf | default(omit) }}"
        state: present
      with_subelements:
        - "{{ netbox_data.devices }}"
        - interfaces
      when: item.1.address is defined
    - name: Create VM ip addresses
      netbox.netbox.netbox_ip_address:
        netbox_url: "{{ lookup('env', 'NETBOX_API') }}"
        netbox_token: "{{ lookup('env', 'NETBOX_TOKEN') }}"
        data:
          address: "{{ item.1.address }}"
          interface: 
            name: "{{ item.1.name }}"
            virtual_machine: "{{ item.0.name }}"
          vrf: "{{ item.1.vrf | default(omit) }}"
        state: present
      with_subelements:
        - "{{ netbox_data.virtual_machines }}"
        - interfaces
      when: item.1.address is defined
    - name: Assign device primary IP addresses
      netbox.netbox.netbox_device:
        netbox_url: "{{ lookup('env', 'NETBOX_API') }}"
        netbox_token: "{{ lookup('env', 'NETBOX_TOKEN') }}"
        data:
          name: "{{ item.name }}"
          primary_ip4: "{{ item.primary_ip4 }}"
      with_items: "{{ netbox_data.devices }}"
      when: item.primary_ip4 is defined
    - name: Assign VM primary IP addresses
      netbox.netbox.netbox_virtual_machine:
        netbox_url: "{{ lookup('env', 'NETBOX_API') }}"
        netbox_token: "{{ lookup('env', 'NETBOX_TOKEN') }}"
        data:
          name: "{{ item.name }}"
          primary_ip4: "{{ item.primary_ip4 }}"
      with_items: "{{ netbox_data.virtual_machines }}"
      when: item.primary_ip4 is defined

    # - name: Delete prefixes
    #   netbox.netbox.netbox_prefix:
    #     netbox_url: "{{ lookup('env', 'NETBOX_API') }}"
    #     netbox_token: "{{ lookup('env', 'NETBOX_TOKEN') }}"
    #     data:
    #       prefix: "{{ item }}"
    #     state: absent
    #   with_items:
    #     - 10.10.20.0/24
    #     - 172.16.101.0/24
    #     - 172.16.102.0/24
    #     - 172.16.103.0/24
    #     - 172.16.104.0/24
    #     - 172.16.105.0/24
    #     - 172.16.252.0/30
    #     - 172.16.252.4/30
    #     - 172.16.252.8/30
    #     - 172.16.252.12/30
    #     - 172.16.252.16/30
    #     - 172.16.252.20/30
    #     - 172.16.252.24/30
    #     - 172.16.252.28/30
    #     - 172.16.252.32/30
    #     - 172.16.252.36/30
    #     - 172.16.253.0/29
    #     - 172.31.0.0/24
    #     - 172.31.252.0/24
    # - name: Delete VLANs
    #   netbox.netbox.netbox_vlan:
    #     netbox_url: "{{ lookup('env', 'NETBOX_API') }}"
    #     netbox_token: "{{ lookup('env', 'NETBOX_TOKEN') }}"
    #     data:
    #       name: "{{ item }}"
    #     state: absent
    #   with_items:
    #     - prod
    #     - dev
    #     - test
    #     - security
    #     - iot
    # - name: Delete VLAN groups
    #   netbox.netbox.netbox_vlan_group:
    #     netbox_url: "{{ lookup('env', 'NETBOX_API') }}"
    #     netbox_token: "{{ lookup('env', 'NETBOX_TOKEN') }}"
    #     data:
    #       name: Sandbox VLAN Group
    #     state: absent        
    # - name: Delete VRFs
    #   netbox.netbox.netbox_vrf:
    #     netbox_url: "{{ lookup('env', 'NETBOX_API') }}"
    #     netbox_token: "{{ lookup('env', 'NETBOX_TOKEN') }}"
    #     data:
    #       name: Enterprise Network
    #     state: absent
    #   ignore_errors: yes
    # - name: Delete device roles
    #   netbox.netbox.netbox_device_role:
    #     netbox_url: "{{ lookup('env', 'NETBOX_API') }}"
    #     netbox_token: "{{ lookup('env', 'NETBOX_TOKEN') }}"
    #     data:
    #       name: "{{ item }}"
    #     state: absent
    #   with_items:
    #     - firewall
    #     - load-balancer
    #     - router
    #     - server
    #     - switch
    # - name: Delete device types
    #   netbox.netbox.netbox_device_type:
    #     netbox_url: "{{ lookup('env', 'NETBOX_API') }}"
    #     netbox_token: "{{ lookup('env', 'NETBOX_TOKEN') }}"
    #     data:
    #       model: "{{ item }}"
    #     state: absent
    #   with_items:
    #     - ASA
    #     - IOS
    #     - IOS XE
    #     - IOS XR
    #     - NX-OS
    #     - Other
