collections:
  # - name: https://github.com/model-driven-devops/ansible-mdd,mdd-dev
  #   type: git
  - name: https://github.com/model-driven-devops/ansible-nso.git
    type: git
  - name: cisco.cml
  - name: netbox.netbox